contacts:
  name: Nebil Rahmeto
  title: Software Engineer
  email: nebilrahmeto2004@gmail.com
  address: "Addis Ababa, Ethiopia"
  location: Ethiopia
  linkedin:
    url: https://www.linkedin.com/in/nebilrahmeto/
    displayText: nebilrahmeto
  github:
    url: https://github.com/patrix726/
    displayText: "@patrix726"
  website:
    url: https://nebil.work
    displayText: nebil.work

position: Software Engineer

tagline: Software engineer with 5 years of experience and a strong foundation in computer science, skilled in developing software for innovative industries. Proficient in JavaScript/TypeScript, Python, and C/C++, with a solid understanding of system architecture and design principles.

jobs:
  - position: Lead Software Developer
    company:
      name: Quantum Innovations
      link: https://quantuminnovations.com/
    product:
      name: QuantumLeap
      link: https://quantumleap.com
    description:
      - Spearheaded the development of a cutting-edge quantum computing simulator, optimizing algorithms for performance.
      - Collaborated with a team to create intuitive user interfaces that simplified complex scientific data for end-users.
    from: "2023 Mar."
    to: "2024 Jul."
    tags:
      - Quantum Computing
      - Algorithm Optimization
      - UI Design
    location: Remote
  - position: Backend Developer
    company:
      name: CloudSync Solutions
      link: https://cloudsyncsolutions.com/
    product:
      name: SyncManager
      link: https://syncmanager.com
    description:
      - Built scalable backend services for SyncManager, ensuring high availability and performance for cloud synchronization.
      - Designed and implemented RESTful APIs to facilitate data exchange between clients and servers.
    from: "2024 Aug."
    to: "present"
    tags:
      - API Development
      - Cloud Computing
      - Microservices
    location: Remote
  - position: DevOps Engineer
    company:
      name: AutoTech Dynamics
      link: https://autotechdynamics.com/
    product:
      name: AutoPilot
      link: https://autopilot.com
    description:
      - Streamlined CI/CD pipelines for the AutoPilot system, enhancing deployment frequency and reliability.
      - Monitored system performance and implemented improvements for optimized infrastructure.
    from: "2022 Feb."
    to: "2023 Dec."
    tags:
      - DevOps
      - CI/CD
      - Infrastructure Management
    location: Denver, USA
  - position: Game Developer
    company:
      name: PixelForge Studios
      link: "https://pixelforgestudios.com/"
    product:
      name: Realm of Adventure
      link: https://realmofadventure.com
    description:
      - Developed engaging gameplay mechanics and interactive environments using Unity and C#.
      - Collaborated with artists to ensure visual consistency and high-quality game experiences.
    from: "2021 Jan."
    to: "2022 Dec."
    tags:
      - Game Development
      - Unity
      - C#
    location: Los Angeles, USA

objective: Seeking to advance my skills and build a strong career with a company that values innovation and creativity.

education:
  - place:
      name: Adama Science and Technology University
      link: "https://www.astu.edu.et"
    degree: "B.Sc."
    major: Software Engineering
    track: Software Engineering
    from: "2022"
    to: "2026"
    location: Adama, Ethiopia

# technical_expertise:
#   - name: Kotlin
#     level: 4
#   - name: Angular
#     level: 5
#   - name: Ruby on Rails
#     level: 5
#   - name: Flutter
#     level: 4
#   - name: Go
#     level: 4
#   - name: Subversion
#     level: 5
#
skills:
  - HTML/CSS
  - Typescript
  - JavaScript
  - Python
  - Java
  - React
  - Next.js
  - Tailwind CSS
  - Node.js
  - Express
  - SQL
  - Docker
  - Git
  - Linux

# methodology:
#   - Lean
#   - Kanban
#   - Design Thinking
#   - Test-Driven Development
#   - Pair Programming
#
tools:
  - GitHub
  - Figma
  - Postman

achievements:
  - name: "Best Project Award"
    description: Developed an innovative solution for community service management and received recognition from the university.
