contacts:
  name: Nebil Rahmeto
  title: Software Engineer
  email: nebilrahmeto2004@gmail.com
  address: "Addis Ababa, Ethiopia"
  location: Ethiopia
  linkedin:
    url: https://www.linkedin.com/in/nebilrahmeto/
    displayText: nebilrahmeto
  github:
    url: https://github.com/patrix726/
    displayText: "@patrix726"
  website:
    url: https://nebil.work
    displayText: nebil.work

position: Software Engineer

tagline: "Software engineer with 4+ years of experience and a strong foundation in computer science and software engineering, skilled in developing software for innovative industries. Proficient in JavaScript/TypeScript, Python, Java, and Dart, with a solid understanding of system architecture and design principles."

jobs:
  - position: Full Stack Developer
    company:
      name: Yourstech Academy
      link: https://yourstech.academy/
    product:
      name: Yourstech Academy
      link: https://yourstech.academy
    description:
      - Built an eLearning platform similar to Udacity, enabling users to purchase courses.
      - Managed database schema and backend development, with contributions to the frontend.
      - Integrated Vimeo for seamless video streaming.
      - Deployed the application to a VPS for production.
    from: "Jun. 2025"
    to: "Dec. 2025"
    tags:
      - Next.js
      - Frontend & Backend
      - Third-party integration
    location: Remote
  - position: Backend Developer
    company:
      name: Ecybernest
      link: https://ecybernest.com/
    product:
      name: Academy Nest
      link: https://academy-nest.com
    description:
      - Built scalable backend services for Academy Nest, ensuring high availability and performance.
      - Designed and implemented RESTful APIs to facilitate data exchange between clients and servers.
      - Integrated live video streaming for teachers to educate students.
    from: "Nov. 2024"
    to: "Mar. 2025"
    tags:
      - API Development
      - Query optimization
      - Zoom integration
      - Express.js
      - Socket.io
    location: Remote
  - position: Full Stack Developer (Intern)
    company:
      name: EagleLion System Technology
      link: https://www.eaglelionsystems.com/
    product:
      name: Electronic Medical Record System
      link: https://emr-system-lake.vercel.app
    description:
      - Implemented role-based access for doctors, patients, receptionists, and admins
      - Built features for patient records management, appointment scheduling, and invoicing
      - Designed secure authentication and dynamic dashboards for different user roles
      - Optimized data handling and system performance to improve hospital
        workflows
    from: "2022 Feb."
    to: "2023 Dec."
    tags:
      - Next.js
      - Prisma
      - Testing
    location: Remote
  - position: Full Stack Developer (Intern) - Network Engineering Department
    company:
      name: Information Network Security Agency
      link: https://www.insa.gov.et/
    product:
      name: Internal Tool (Web based network dashboard)
      link: "#"
    description:
      - Built a web-based dashboard for real-time visualization of network topology
      - Integrated and updated the L2Switch module to make it compatible with
        the latest OpenDaylight version, utilizing a previously unmaintained
        open-source project.
      - Designed and tested simulated SDN environments using Mininet to validate controller behavior
    from: "Jun. 2025"
    to: "Sep. 2025"
    tags:
      - Opendaylight
      - React.js
      - Express
    location: Wollo Sefer, Addis Ababa

objective: Seeking to advance my skills and build a strong career with a company that values innovation and creativity.

education:
  - place:
      name: Adama Science and Technology University
      link: "https://www.astu.edu.et"
    degree: "B.Sc."
    major: Software Engineering
    track: Software Engineering
    from: "2022"
    to: "2026"
    location: Adama, Ethiopia

# technical_expertise:
#   - name: Kotlin
#     level: 4
#   - name: Angular
#     level: 5
#   - name: Ruby on Rails
#     level: 5
#   - name: Flutter
#     level: 4
#   - name: Go
#     level: 4
#   - name: Subversion
#     level: 5
#
skills:
  - HTML/CSS
  - Typescript
  - JavaScript
  - Python
  - Java
  - Dart
  - React
  - Next.js
  - Tailwind CSS
  - Flutter
  - Node.js
  - Express
  - SQL
  - Docker
  - Git
  - Linux

# methodology:
#   - Lean
#   - Kanban
#   - Design Thinking
#   - Test-Driven Development
#   - Pair Programming
#
tools:
  - GitHub
  - Figma
  - Postman

achievements:
  - name: "Best Project Award"
    description: Developed an innovative solution for community service management and received recognition from the university.
