name: Resume Release Pipeline

on: [push, workflow]

permissions:
  contents: write

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Typst
        uses: lvignoli/typst-action@main
        with:
          source_file: resume.typ

      - name: Upload PDF file
        uses: actions/upload-artifact@v4
        with:
          name: PDF
          path: *.pdf
      - name: Get current date
        id: date
        run: echo "DATE=$(date +%Y-%m-%d-%H:%M)" >> $GITHUB_ENV

      - name: Release
        uses: softprops/action-gh-release@v1
        if: github.ref_type == 'tag'
        with:
          name: "${{ github.ref_name }} â€” ${{ env.DATE }}"
          files: main.pdf

  # create-release:
  #   needs: build-and-test
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout code
  #       uses: actions/checkout@v4
  #
  #     # You can use a predefined action to create a release from a tag
  #     # This action requires you to have a versioning strategy (e.g., semantic versioning)
  #     # You would typically have a separate step or action to manage the tag creation
  #     - name: Create Release
  #       id: create_release
  #       uses: actions/create-release@v1
  #       env:
  #         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  #       with:
  #         tag_name: v1.0.${{ github.run_number }} # Example: uses the run number for a unique tag
  #         release_name: Release v1.0.${{ github.run_number }}
  #         body: |
  #           Automated release based on successful build ${{ github.run_number }}.
  #         draft: false
  #         prerelease: false
